# Generated by Django 3.0.5 on 2020-05-24 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_subject_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='slug',
        ),
    ]
